# Generated by Django 5.1.5 on 2025-05-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locatie',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='location_photos/'),
        ),
        migrations.AddField(
            model_name='team',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
    ]
